type MaterialList = {
  row_id: number;
  line_row_id_front: number;
  attribute_guid: string;
  attribute_name: string;
  mtrl_guid: string;
  mtrl_code: string;
  mtrl_name: string;
  mtrl_full_name: string;
  mtrl_desc: string;
  mtrl_type_code: string;
  unit_det_name: string;
  unit_det_numerator: number;
  unit_det_dominator: number;
  price_type_guid: string;
  price_guid: string;
  price_value: any;
  price_total: string;
  amount: number;
  price_type_name: string;
  group_guid: string;
  image_name: string;
  changedPrice?: number;
  priceType?: string;
  ord_line_desc?: string;
  stock_amount?: number;
};
export default MaterialList;
